dist: focal
language: java

addons:
  sonarcloud:
    organization: "techteamer"
  apt:
    packages:
      - rabbitmq-server

env:
  - TEST_ENV=travis

script:
  - ./gradlew test jacocoTestReport sonarqube --info
