os: linux
dist: focal

env:
  - TEST_ENV=travis

language: java

cache: false

git:
  depth: false

addons:
  apt:
    packages:
      - rabbitmq-server
  sonarcloud:
    organization: "techteamer"

stages:
  - name: test
    if: branch =~ /(^(main|devel\/.+?)$)|(^(feature|cr|debug|fix|update|upgrade|patch|mod|modification|doc|documentation|test|refact|refactor|improve|improvement)\/[A-Z]+\-\d+(\-.+)?)$/
  - name: release
    if: tag = latest

jobs:
  include:
    - stage: test
      name: unit tests and code quality # https://docs.travis-ci.com/user/build-matrix/#explicitly-included-jobs-with-only-one-element-in-the-build-matrix
      script:
        - ./gradlew test jacocoTestReport sonarqube --info
    - stage: release
      name: publish release
      script:
        - ./bin/publish.sh $SONATYPE_USERNAME $SONATYPE_PASSWORD $GPG_KEY_ID $GPG_PASSWORD $GPG_KEY
