os: linux
dist: focal

env:
  - TEST_ENV=travis

language: bash

cache: false
git:
  depth: false
branches:
  only:
    - /(^(main|devel\/.+?)$)|(^(feature|cr|debug|fix|update|upgrade|patch|mod|modification|doc|documentation|test|refact|refactor|improve|improvement)\/[A-Z]+\-\d+(\-.+)?)$/
    - /^(latest|\d+\.\d+\.\d+)$/

#addons:
#  sonarcloud:
#    organization: "techteamer"
#  apt:
#    packages:
#      - rabbitmq-server
stages:
  - test
  - name: release
    if: tag = latest

jobs:
  include:
    - stage: test
      name: code quality # https://docs.travis-ci.com/user/build-matrix/#explicitly-included-jobs-with-only-one-element-in-the-build-matrix
      script:
        - echo "Testing code quality for $TRAVIS_BRANCH"
#        - ./gradlew test jacocoTestReport sonarqube --info
#        - ./src/test/scripts/travis.sh
    - stage: release
      name: publish release
      script:
        - ./publish.sh $GPG_KEY_ID $GPG_PASSWORD $SONATYPE_USERNAME $SONATYPE_PASSWORD
