os: linux
dist: focal

env:
  - TEST_ENV=travis

language: java

cache: false
git:
  depth: false

addons:
  sonarcloud:
    organization: "techteamer"
  apt:
    packages:
      - rabbitmq-server
stages:
  - name: test
    if: branch =~ /(^(main|devel\/.+?)$)|(^(feature|cr|debug|fix|update|upgrade|patch|mod|modification|doc|documentation|test|refact|refactor|improve|improvement)\/[A-Z]+\-\d+(\-.+)?)$/
  - name: release
    if: (branch = main) AND (tag = latest)

jobs:
  include:
    - stage: test
      name: code quality # https://docs.travis-ci.com/user/build-matrix/#explicitly-included-jobs-with-only-one-element-in-the-build-matrix
      script:
#        - ./gradlew test jacocoTestReport sonarqube --info
#        - ./src/test/scripts/travis.sh
        - echo hello test
    - stage: release
      name: publish release
      after_success:
        - echo hello $TRAVIS_TAG
